import { exec as execCb } from "node:child_process";
import fs from "node:fs/promises";
import { promisify } from "node:util";
import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  expect,
  test,
} from "vitest";

const exec = promisify(execCb);

const writePrismaConfigFile = async (url: string) => {
  await fs.writeFile(
    "./prisma.config.ts",
    `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: ${url},
  },
});
`
  );
};

// prisma is creating entries in .gitignore without looking inside if that entry
// exists already (in this case "src/generated/prisma"). This creates 13 extra
// entries, one per test run. We are just moving the real .gitignore out of the
// way for tests and replace it with the test generated one after all tests
// ran
beforeAll(async () => {
  await fs.rename("./.gitignore", "./.gitignore-old");
});

afterAll(async () => {
  await fs.rm("./.gitignore");
  await fs.rename("./.gitignore-old", "./.gitignore");
});

beforeEach(async () => {
  await fs.rename("./prisma", "./prisma-old").catch(() => {});
  await fs.rm("./generated/prisma", { force: true });
});

afterEach(async () => {
  await fs
    .rm("./prisma", {
      force: true,
      recursive: true,
    })
    .catch(() => {});
  await fs.rename("./prisma-old", "./prisma").catch(() => {});
  await fs.rm("./generated/prisma", { force: true });
  await fs.rm("./dev.db", { force: true });
  await fs.rm("./prisma.config.ts", { force: true });
});

test("End to end test", { timeout: 20000 }, async () => {
  // Initialize prisma:
  await exec("yarn prisma init --datasource-provider sqlite");

  await writePrismaConfigFile('"file:./dev.db"');

  // Set up a schema
  await fs.writeFile(
    "./prisma/schema.prisma",
    `datasource db {
        provider = "sqlite"
    }

    generator client {
      provider = "prisma-client"
      output   = "./generated/prisma"
    }

    generator kysely {
        provider  = "node ./dist/bin.js"
    }

    model TestUser {
        id          String @id
        name        String
        age         Int
        rating      Float
        updatedAt   DateTime
        sprockets   Sprocket[]
    }

    model Sprocket {
        id          Int @id
        users       TestUser[]
    }`
  );

  // Run Prisma commands without fail
  await exec("yarn prisma generate");

  const generatedSource = await fs.readFile("./prisma/generated/types.ts", {
    encoding: "utf-8",
  });

  expect(generatedSource).toContain(`export type SprocketToTestUser = {
    A: number;
    B: string;
};`);

  expect(generatedSource).toContain("_SprocketToTestUser: SprocketToTestUser");

  // Expect no Kysely wrapped types to be exported since we don't enable exportWrappedTypes
  expect(generatedSource).not.toContain("Insertable");
});

test(
  "End to end test - with custom type override",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider sqlite");

    await writePrismaConfigFile('"file:./dev.db"');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
    datasource db {
        provider = "sqlite"
    }
    
    generator client {
      provider = "prisma-client"
      output   = "./generated/prisma"
    }

    generator kysely {
        provider  = "node ./dist/bin.js"
    }

    model TestUser {
        id          String @id
        name        String

        /// @kyselyType('member' | 'owner')
        role        String
    }`
    );

    // Run Prisma commands without fail
    await exec("yarn prisma generate");

    const generatedSource = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    // Expect many to many models to have been generated
    expect(generatedSource).toContain(
      `export type TestUser = {
    id: string;
    name: string;
    /**
     * @kyselyType('member' | 'owner')
     */
    role: 'member' | 'owner';
};`
    );
  }
);

test("End to end test - separate entrypoints", { timeout: 20000 }, async () => {
  // Initialize prisma:
  await exec("yarn prisma init --datasource-provider mysql");

  await writePrismaConfigFile('"mysql://root:password@localhost:3306/test"');

  // Set up a schema
  await fs.writeFile(
    "./prisma/schema.prisma",
    `
    datasource db {
        provider = "mysql"
    }

    generator client {
      provider = "prisma-client"
      output   = "./generated/prisma"
    }
    
    generator kysely {
        provider  = "node ./dist/bin.js"
        enumFileName = "enums.ts"
    }

    enum TestEnum {
        A
        B
        C
    }

    model TestUser {
        id          String @id
        name        String
        age         Int
        rating      Float
        updatedAt   DateTime
        abc         TestEnum
    }`
  );

  // Run Prisma commands without fail
  // await exec("yarn prisma db push"); -- can't push to mysql, enums not supported in sqlite
  await exec("yarn prisma generate"); //   so just generate

  const typeFile = await fs.readFile("./prisma/generated/types.ts", {
    encoding: "utf-8",
  });
  expect(typeFile).not.toContain("export const");
  expect(typeFile).toContain(`import type { TestEnum } from "./enums";`);

  const enumFile = await fs.readFile("./prisma/generated/enums.ts", {
    encoding: "utf-8",
  });
  expect(enumFile).toEqual(`export const TestEnum = {
    A: "A",
    B: "B",
    C: "C"
} as const;
export type TestEnum = (typeof TestEnum)[keyof typeof TestEnum];
`);
});

test(
  "End to end test - separate entrypoints but no enums",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider sqlite");

    await writePrismaConfigFile('"file:./dev.db"');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
    datasource db {
        provider = "sqlite"
    }

    generator client {
      provider = "prisma-client"
      output   = "./generated/prisma"
    }
    
    generator kysely {
        provider  = "node ./dist/bin.js"
        enumFileName = "enums.ts"
    }

    model TestUser {
        id          String @id
        name        String
        age         Int
        rating      Float
        updatedAt   DateTime
    }`
    );

    // Run Prisma commands without fail
    await exec("yarn prisma db push");
    await exec("yarn prisma generate");

    // Shouldn't have an empty import statement
    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });
    expect(typeFile).not.toContain('from "./enums"');

    // Shouldn't have generated an empty file
    await expect(
      fs.readFile("./prisma/generated/enums.ts", {
        encoding: "utf-8",
      })
    ).rejects.toThrow();
  }
);

test("End to end test - multi-schema support", { timeout: 20000 }, async () => {
  // Initialize prisma:
  await exec("yarn prisma init --datasource-provider postgresql");

  await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

  // Set up a schema
  await fs.writeFile(
    "./prisma/schema.prisma",
    `
    generator kysely {
        provider  = "node ./dist/bin.js"
        previewFeatures = ["multiSchema"]
    }

    generator client {
      provider = "prisma-client"
      output   = "./generated/prisma"
    }

    datasource db {
        provider = "postgresql"
        schemas  = ["mammals", "birds"]
    }

    model Elephant {
        id   Int    @id
        name String

        @@map("elephants")
        @@schema("mammals")
    }

    model Eagle {
        id   Int    @id
        name String

        @@map("eagles")
        @@schema("birds")
    }`
  );

  await exec("yarn prisma generate");

  // Shouldn't have an empty import statement
  const typeFile = await fs.readFile("./prisma/generated/types.ts", {
    encoding: "utf-8",
  });

  expect(typeFile).toContain(`export type DB = {
    "birds.eagles": Eagle;
    "mammals.elephants": Elephant;
};`);
});

test(
  "End to end test - multi-schema and filterBySchema support",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider postgresql");

    await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
    generator kysely {
        provider  = "node ./dist/bin.js"
        previewFeatures = ["multiSchema"]
        filterBySchema = ["mammals"]
    }

    generator client {
        provider = "prisma-client"
        output   = "./generated/prisma"
    }
    
    datasource db {
        provider = "postgresql"
        schemas  = ["mammals", "birds"]
    }

    model Elephant {
        id   Int    @id
        name String

        @@map("elephants")
        @@schema("mammals")
    }

    model Eagle {
        id   Int    @id
        name String

        @@map("eagles")
        @@schema("birds")
    }`
    );

    await exec("yarn prisma generate");

    // Shouldn't have an empty import statement
    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    expect(typeFile).toContain(`export type DB = {
    "mammals.elephants": Elephant;
};`);
  }
);

test(
  "End to end test - multi-schema and groupBySchema support",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider postgresql");

    await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
generator kysely {
    provider        = "node ./dist/bin.js"
    previewFeatures = ["multiSchema"]
    groupBySchema   = true
}

generator client {
    provider = "prisma-client"
    output   = "./generated/prisma"
}

datasource db {
    provider = "postgresql"
    schemas  = ["mammals", "birds", "world"]
}

model Elephant {
    id      Int     @id
    name    String
    ability Ability @default(WALK)
    color  Color

    @@map("elephants")
    @@schema("mammals")
}

model Eagle {
    id      Int     @id
    name    String
    ability Ability @default(FLY)

    @@map("eagles")
    @@schema("birds")
}

enum Ability {
    FLY
    WALK

    @@schema("world")
}

enum Color {
  GRAY
  PINK

  @@schema("mammals")
}
    `
    );

    await exec("yarn prisma generate");

    // Shouldn't have an empty import statement
    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    expect(typeFile).toContain(`export namespace Birds {
    export type Eagle = {`);

    expect(typeFile).toContain(`export namespace Mammals {
    export const Color = {`);

    // correctly references the color enum
    expect(typeFile).toContain("color: Mammals.Color;");

    expect(typeFile).toContain(`export type DB = {
    "birds.eagles": Birds.Eagle;
    "mammals.elephants": Mammals.Elephant;
};`);
  }
);

test(
  "End to end test - multi-schema, groupBySchema and defaultSchema support",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider postgresql");

    await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
generator kysely {
    provider        = "node ./dist/bin.js"
    previewFeatures = ["multiSchema"]
    groupBySchema   = true
    defaultSchema   = "fish"
}
generator client {
    provider = "prisma-client"
    output   = "./generated/prisma"
}

datasource db {
    provider = "postgresql"
    schemas  = ["mammals", "birds", "world", "fish"]
}

model Elephant {
    id      Int     @id
    name    String
    ability Ability @default(WALK)
    color  Color

    @@map("elephants")
    @@schema("mammals")
}

model Eagle {
    id      Int     @id
    name    String
    ability Ability @default(FLY)

    @@map("eagles")
    @@schema("birds")
}

model Shark {
    id      Int     @id
    name    String
    color  Color

    @@map("shark")
    @@schema("fish")
}

enum Ability {
    FLY
    WALK

    @@schema("world")
}

enum Color {
  GRAY
  PINK

  @@schema("mammals")
}
    `
    );

    await exec("yarn prisma generate");

    // Shouldn't have an empty import statement
    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    expect(typeFile).toContain(`export namespace Birds {
    export type Eagle = {`);

    expect(typeFile).toContain(`export namespace Mammals {
    export const Color = {`);

    // outside of enum
    expect(typeFile).toContain("export type Shark = {");

    // correctly references the color enum
    expect(typeFile).toContain("color: Mammals.Color;");

    expect(typeFile).toContain(`export type DB = {
    "birds.eagles": Birds.Eagle;
    "mammals.elephants": Mammals.Elephant;
    shark: Shark;
};`);
  }
);

test(
  "End to end test - multi-schema, groupBySchema and filterBySchema support",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider postgresql");

    await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
generator kysely {
    provider        = "node ./dist/bin.js"
    previewFeatures = ["multiSchema"]
    groupBySchema   = true
    filterBySchema = ["mammals", "world"]
}

generator client {
    provider = "prisma-client"
    output   = "./generated/prisma"
}


datasource db {
    provider = "postgresql"
    schemas  = ["mammals", "birds", "world"]
}

model Elephant {
    id      Int     @id
    name    String
    ability Ability @default(WALK)
    color  Color

    @@map("elephants")
    @@schema("mammals")
}

model Eagle {
    id      Int     @id
    name    String
    ability Ability @default(FLY)

    @@map("eagles")
    @@schema("birds")
}

enum Ability {
    FLY
    WALK

    @@schema("world")
}

enum Color {
  GRAY
  PINK

  @@schema("mammals")
}
    `
    );

    await exec("yarn prisma generate");

    // Shouldn't have an empty import statement
    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    expect(typeFile).not.toContain(`export namespace Birds {
    export type Eagle = {`);

    expect(typeFile).toContain(`export namespace Mammals {
    export const Color = {`);

    // correctly references the color enum
    expect(typeFile).toContain("color: Mammals.Color;");

    expect(typeFile).toContain(`export type DB = {
    "mammals.elephants": Mammals.Elephant;
};`);
  }
);

test(
  "End to end test - SQLite with JSON support",
  { timeout: 20000 },
  async () => {
    await exec("yarn prisma init --datasource-provider sqlite");

    await writePrismaConfigFile('"file:./dev.db"');

    await fs.writeFile(
      "./prisma/schema.prisma",
      `
    datasource db {
        provider = "sqlite"
    }

    generator kysely {
        provider  = "node ./dist/bin.js"
    }
    
    generator client {
        provider = "prisma-client"
        output   = "./generated/prisma"
    }


    model TestUser {
        id          String   @id
        name        String
        metadata    Json     // JSON field supported in SQLite since Prisma 6.2
        preferences Json?    // Optional JSON field

        /// @kyselyType({ theme: 'light' | 'dark', language: string })
        settings    Json

        createdAt   DateTime @default(now())
    }

    model Product {
        id          Int      @id @default(autoincrement())
        name        String
        details     Json     // Product details as JSON

        /// @kyselyType(string[])
        tags        Json?    // Optional tags as JSON array
    }`
    );

    await exec("yarn prisma generate");

    const generatedSource = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    expect(generatedSource).toContain(`export type TestUser = {
    id: string;
    name: string;
    metadata: unknown;
    preferences: unknown | null;
    /**
     * @kyselyType({ theme: 'light' | 'dark', language: string })
     */
    settings: { theme: 'light' | 'dark', language: string };
    createdAt: Generated<string>;
};`);

    expect(generatedSource).toContain(`export type Product = {
    id: Generated<number>;
    name: string;
    details: unknown;
    /**
     * @kyselyType(string[])
     */
    tags: string[] | null;
};`);

    expect(generatedSource).toContain(`export type DB = {
    Product: Product;
    TestUser: TestUser;
};`);
  }
);

test(
  "End to end test - multi-schema with views support",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider postgresql");

    await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

    // Set up a schema with views in different schemas
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
    generator kysely {
        provider        = "node ./dist/bin.js"
        previewFeatures = ["multiSchema", "views"]
    }
    
    generator client {
        provider = "prisma-client"
        output   = "./generated/prisma"
    }

    datasource db {
        provider = "postgresql"
        schemas  = ["public", "analytics"]
    }

    model User {
        id      Int    @id
        name    String
        email   String
        posts   Post[]

        @@schema("public")
    }

    model Post {
        id       Int    @id
        title    String
        content  String
        authorId Int
        author   User   @relation(fields: [authorId], references: [id])

        @@schema("public")
    }

    view UserStats {
        id        Int    @unique
        name      String
        postCount Int

        @@schema("analytics")
    }

    view PostSummary {
        id      Int    @unique
        title   String
        author  String

        @@schema("public")
    }`
    );

    await exec("yarn prisma generate");

    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    // Verify that views are properly prefixed with their schema names
    expect(typeFile).toContain(`export type DB = {
    "analytics.UserStats": UserStats;
    Post: Post;
    PostSummary: PostSummary;
    User: User;
};`);

    // Verify view types are generated correctly
    expect(typeFile).toContain(`export type UserStats = {
    id: number;
    name: string;
    postCount: number;
};`);

    expect(typeFile).toContain(`export type PostSummary = {
    id: number;
    title: string;
    author: string;
};`);
  }
);

test("End to end test - exportWrappedTypes", { timeout: 20000 }, async () => {
  await exec("yarn prisma init --datasource-provider sqlite");

  await writePrismaConfigFile('"file:./dev.db"');

  await fs.writeFile(
    "./prisma/schema.prisma",
    `
      datasource db {
          provider = "sqlite"
      }
  
      generator kysely {
          provider           = "node ./dist/bin.js"
          exportWrappedTypes = true
      }
      
      generator client {
          provider = "prisma-client"
          output   = "./generated/prisma"
      }

      
      model User {
          id   String @id
          name String
      }`
  );

  await exec("yarn prisma generate");

  const generatedSource = await fs.readFile("./prisma/generated/types.ts", {
    encoding: "utf-8",
  });

  expect(generatedSource).toContain("export type UserTable = {");
  expect(generatedSource).toContain(
    "export type User = Selectable<UserTable>;"
  );
  expect(generatedSource).toContain(
    "export type NewUser = Insertable<UserTable>;"
  );
  expect(generatedSource).toContain(
    "export type UserUpdate = Updateable<UserTable>;"
  );
  expect(generatedSource).toContain(
    "export type DB = {\n    User: UserTable;\n};"
  );
});

test(
  "End to end test - groupBySchema and exportWrappedTypes support",
  { timeout: 20000 },
  async () => {
    // Initialize prisma:
    await exec("yarn prisma init --datasource-provider postgresql");

    await writePrismaConfigFile('process.env["TEST_DATABASE_URL"]');

    // Set up a schema
    await fs.writeFile(
      "./prisma/schema.prisma",
      `
generator kysely {
    provider             = "node ./dist/bin.js"
    previewFeatures      = ["multiSchema"]
    groupBySchema        = true
    exportWrappedTypes   = true
}

generator client {
    provider = "prisma-client"
    output   = "./generated/prisma"
}


datasource db {
    provider = "postgresql"
    schemas  = ["mammals", "birds", "world"]
}

model Elephant {
    id      Int     @id
    name    String
    ability Ability @default(WALK)
    color  Color

    @@map("elephants")
    @@schema("mammals")
}

model Eagle {
    id      Int     @id
    name    String
    ability Ability @default(FLY)

    @@map("eagles")
    @@schema("birds")
}

enum Ability {
    FLY
    WALK

    @@schema("world")
}

enum Color {
  GRAY
  PINK

  @@schema("mammals")
}
    `
    );

    await exec("yarn prisma generate");

    // Shouldn't have an empty import statement
    const typeFile = await fs.readFile("./prisma/generated/types.ts", {
      encoding: "utf-8",
    });

    expect(typeFile).toContain(`export namespace Birds {
    export type EagleTable = {`);

    expect(typeFile).toContain(`export namespace Mammals {
    export const Color = {`);

    // correctly references the color enum
    expect(typeFile).toContain("color: Mammals.Color;");

    expect(typeFile).toContain(`export type DB = {
    "birds.eagles": Birds.EagleTable;
    "mammals.elephants": Mammals.ElephantTable;
};`);
  }
);
