name: 😵‍💫 Sanity checks
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: 🏗 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: 🧪 Run tests
        run: bun run test

  typecheck:
    name: 🤓 Type checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: 🏗 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: 🤓 Run type checker
        run: bun run typecheck

  lint:
    name: 👮‍♂️ Linters and formatters
    runs-on: ubuntu-latest
    permissions:
      checks: write # Allow creating checks
      contents: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: 🏗 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: 👮‍♂️ Run linters
        run: bun run lint

      - name: 💅 Run fixers, and check diff
        id: diffCheck
        run: bun run fix && git diff --exit-code -- ':!bun.lock'

      - name: 💬 Post a check explaining the issue
        if: ${{ failure() && steps.diffCheck.conclusion == 'failure' }}
        uses: LouisBrunner/checks-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 🧹 Check all files are formatted correctly
          conclusion: failure
          output: |
            {"summary": "Hrm, seems like you don't have prettier set up properly. Make sure your editor is configured to format code automatically, and that it respects the project's prettier config. [Click here](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) to view the Prettier extension for VS Code.\n\n> _**💡 Tip:**_ \n> \n> In the meantime you can run `bun run fix` and commit the changes."}
